debug: ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,14 +60,14 @@ jobs:
 
     steps:
       - name: Wait for Postgres
-          run: |
-            for i in {1..15}; do
-              pg_isready -h postgres -U user && echo "Postgres is ready!" && exit 0
-              echo "Waiting for Postgres... ($i)"
-              sleep 2
-            done
-            echo "Postgres failed to start in time" >&2
-            exit 1
+        run: |
+          for i in {1..15}; do
+            pg_isready -h postgres -U user && echo "Postgres is ready!" && exit 0
+            echo "Waiting for Postgres... ($i)"
+            sleep 2
+          done
+          echo "Postgres failed to start in time" >&2
+          exit 1
         env:
           PGPASSWORD: password
 
