debug: ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,17 +59,17 @@ jobs:
       DATABASE_NAME: database
 
     steps:
-      - name: Wait for Postgres
-        run: |
-          for i in {1..15}; do
-            pg_isready -h postgres -U user && echo "Postgres is ready!" && exit 0
-            echo "Waiting for Postgres... ($i)"
-            sleep 2
-          done
-          echo "Postgres failed to start in time" >&2
-          exit 1
-        env:
-          PGPASSWORD: password
+      # - name: Wait for Postgres
+      #   run: |
+      #     for i in {1..15}; do
+      #       pg_isready -h postgres -U user && echo "Postgres is ready!" && exit 0
+      #       echo "Waiting for Postgres... ($i)"
+      #       sleep 2
+      #     done
+      #     echo "Postgres failed to start in time" >&2
+      #     exit 1
+      #   env:
+      #     PGPASSWORD: password
 
       - name: Checkout code
         uses: actions/checkout@v4
